# Generated by Django 3.0.6 on 2020-05-14 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar', '0002_marca_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCombustible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('no_chasis', models.CharField(max_length=17)),
                ('no_motor', models.CharField(max_length=9)),
                ('no_placa', models.CharField(max_length=10)),
                ('estado', models.BooleanField()),
                ('combustible_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar.TipoCombustible')),
                ('marca_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar.Marca')),
                ('modelo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar.Modelo')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar.TipoVehiculo')),
            ],
        ),
    ]
