# Generated by Django 3.0.6 on 2020-05-15 00:49

import django.core.validators
from django.db import migrations, models
import rentcar.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar', '0004_auto_20200514_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('cedula', models.CharField(max_length=13, unique=True, validators=[rentcar.validators.validate_cedula])),
                ('tanda_labor', models.CharField(choices=[('M', 'Matutina'), ('V', 'Vespertina'), ('N', 'Nocturna')], max_length=100)),
                ('porciento_comision', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('fecha_ingreso', models.DateField(auto_now=True)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(max_length=13, unique=True, validators=[rentcar.validators.validate_cedula]),
        ),
    ]
