# Generated by Django 3.0.6 on 2020-05-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar', '0005_auto_20200514_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipocombustible',
            options={'verbose_name_plural': 'Tipos de combustible'},
        ),
        migrations.AlterModelOptions(
            name='tipovehiculo',
            options={'verbose_name_plural': 'Tipos de vehiculos'},
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='imagen',
            field=models.ImageField(default='placeholder.jpg', upload_to='imgvehiculos'),
        ),
    ]
