# Generated by Django 3.0.6 on 2020-05-15 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar', '0008_auto_20200514_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspeccion',
            options={'verbose_name_plural': 'Inspecciones'},
        ),
        migrations.RenameField(
            model_name='inspeccion',
            old_name='inspeccion_cliente',
            new_name='cliente',
        ),
    ]
