# Generated by Django 3.0.6 on 2020-05-15 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar', '0009_auto_20200514_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_renta', models.DateField()),
                ('fecha_devolucion', models.DateField()),
                ('monto_por_dia', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cantidad_dias', models.PositiveIntegerField()),
                ('comentario', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar.Cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar.Empleado')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar.Vehiculo')),
            ],
        ),
    ]
