# Generated by Django 3.0.6 on 2020-05-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar', '0010_renta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renta',
            name='fecha_devolucion',
            field=models.DateField(blank=True),
        ),
    ]
