# Generated by Django 3.0.6 on 2020-05-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar', '0011_auto_20200515_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renta',
            name='fecha_devolucion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
