# Generated by Django 3.0.6 on 2020-05-16 02:18

from django.db import migrations, models
import rentcar.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar', '0013_auto_20200515_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tarjeta_credito',
            field=models.CharField(default='4929095510866734', max_length=20, validators=[rentcar.validators.validate_cc]),
        ),
    ]
